# Generated by Django 4.1.7 on 2023-03-02 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_autor', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=15)),
                ('nif', models.IntegerField()),
            ],
            options={
                'db_table': 'contas',
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponivel', models.BooleanField()),
                ('id_exemplar', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'exemplar',
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20)),
                ('editora', models.CharField(max_length=30)),
                ('ano', models.IntegerField()),
                ('idioma', models.CharField(max_length=20)),
                ('titulo_do_livro', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'livros',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coluna', models.CharField(max_length=4)),
                ('prateleira', models.CharField(max_length=4)),
                ('estante', models.CharField(max_length=4)),
                ('n_registo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.exemplar')),
            ],
            options={
                'db_table': 'local',
            },
        ),
        migrations.AddField(
            model_name='exemplar',
            name='id_livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.livros'),
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_req', models.DateField()),
                ('data_ent', models.DateField()),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.contas')),
                ('n_registo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.exemplar')),
            ],
            options={
                'db_table': 'emprestimos',
            },
        ),
        migrations.CreateModel(
            name='Autoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.autores')),
                ('id_livro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.livros')),
            ],
            options={
                'db_table': 'autoria',
                'unique_together': {('id_livro', 'id_autor')},
            },
        ),
    ]
